# Generated by Django 2.2.3 on 2019-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addnewevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=70, verbose_name='Event Name')),
                ('Eventtheme', models.TextField(max_length=500, verbose_name='Event Theme')),
                ('Eventvenue', models.CharField(max_length=50, verbose_name='Event Venue')),
                ('Eventorganizer', models.CharField(max_length=80, verbose_name='Event Organizer')),
                ('Eventmanager', models.CharField(max_length=50, verbose_name='Event Manager')),
                ('Seats', models.IntegerField(verbose_name='Number Of Guests allowed')),
                ('geda', models.CharField(default='hey', max_length=30)),
                ('Picture', models.CharField(max_length=100, default="image.jpg"))
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=50)),
                ('College_name', models.CharField(max_length=55)),
                ('Faculty', models.CharField(choices=[('B.Sc.Cs.It', 'B.Sc.Cs.It'), ('B.CA', 'B.CA'), ('B.IM', 'B.IM')], max_length=20)),
                ('Semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_no', models.IntegerField(default=0)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
