# Generated by Django 2.2.3 on 2019-08-09 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Indrenievents', '0002_auto_20190808_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addnewevent',
            old_name='Seats',
            new_name='Eventcapacity',
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of event'),
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventfinishtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Finishing Time of Event'),
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventlogo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name='Logo Of Event'),
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventperiod',
            field=models.IntegerField(default='1', verbose_name='Event Duration In Days'),
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventposted',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addnewevent',
            name='Eventstarttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time of Event'),
        ),
    ]
