# Generated by Django 2.2.3 on 2019-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indrenievents', '0003_auto_20190809_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewevent',
            name='Eventlogo',
            field=models.ImageField(default='images.jpg', upload_to='event_logos/', verbose_name='Logo Of Event'),
        ),
        migrations.AlterField(
            model_name='addnewevent',
            name='Eventtheme',
            field=models.TextField(max_length=1500, verbose_name='Event Theme'),
        ),
    ]
