# Generated by Django 2.2.3 on 2019-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indrenievents', '0004_auto_20190821_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewevent',
            name='Eventlogo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name='Logo Of Event'),
        ),
    ]
